import React, { useState } from 'react';
import { useTasks } from '../../hooks/useTasks';
import { TaskCard } from '../../components/ui/TaskCard';
import { SkeletonLoader } from '../../components/common/SkeletonLoader';
import { EmptyState } from '../../components/common/EmptyState';
import { CheckSquare } from 'lucide-react';


export const TasksPage: React.FC = () => {
  const { tasks, isLoading, toggleTaskStatus } = useTasks();
  const [filter, setFilter] = useState<'all' | 'todo' | 'completed'>('all');

  const filteredTasks = tasks.filter((t) => {
    if (filter === 'todo') return t.status === 'todo';
    if (filter === 'completed') return t.status === 'completed';
    return true;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-extrabold font-headline text-on-surface">Extracted Action Items</h2>
          <p className="text-xs text-on-surface-variant mt-1">
            Automated checklist generated by MailPilot AI from your inbox threads.
          </p>
        </div>

        <div className="flex gap-2 bg-surface-container-low p-1 rounded-2xl border border-white/10">
          {(['all', 'todo', 'completed'] as const).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-3 py-1.5 text-xs font-bold capitalize rounded-xl transition-all ${
                filter === f
                  ? 'bg-primary text-on-primary shadow-sm'
                  : 'text-on-surface-variant hover:text-on-surface'
              }`}
            >
              {f}
            </button>
          ))}
        </div>
      </div>

      {isLoading ? (
        <div className="space-y-3">
          <SkeletonLoader count={4} className="h-24" />
        </div>
      ) : filteredTasks.length === 0 ? (
        <EmptyState
          title="No tasks found"
          description="All extracted action items are cleared or match your active filter."
          icon={<CheckSquare className="w-12 h-12 text-on-surface-variant/40" />}
        />
      ) : (
        <div className="space-y-3">
          {filteredTasks.map((task) => (
            <TaskCard key={task.id} task={task} onToggleStatus={toggleTaskStatus} />
          ))}
        </div>
      )}
    </div>
  );
};
